CYYZ: toronto-pearson-international-airport_canada_6296338
EDDM: munich-international-airport_germany_3208399
EFHK: helsinki-airport_finland_6301511
EGLC: london-city-airport_united-kingdom_6296599
EHAM: amsterdam-airport-schiphol_the-netherlands_6296680
EPWA: warsaw-chopin-airport_poland_6296786
KATL: hartsfield-jackson-atlanta-international-airport_united-states_4199556
KBKF: buckley-air-force-base_united-states_5415293
KDAL: dallas-love-field_united-states_4684922
KLAX: los-angeles-international-airport_united-states_5368418
KLGA: laguardia-airport_united-states_5123698
KMIA: miami-international-airport_united-states_4164181
KSEA: seattle-tacoma-international-airport_united-states_5809876
KSFO: san-francisco-international-airport_united-states_5391989
LEMD: adolfo-su%c3%a1rez-madrid%e2%80%93barajas-airport_spain_6299345
LFPB: paris%e2%80%93le-bourget-airport_france_2988502
LIMC: milano-malpensa-airport_italy_3174133
LLBG: ben-gurion-airport_israel_390285
LTAC: ankara-esenbo%c4%9fa-international-airport_republic-of-t%c3%bcrkiye_6299725
LTFM: istanbul-airport_republic-of-t%c3%bcrkiye_11838481
MMMX: benito-ju%c3%a1rez-international-airport_mexico_6299859
MPMG: albrook-marcos-a.-gelabert-international-airport_panama_3704579
NZWN: wellington-international-airport_new-zealand_6244688
OEJN: jeddah-king-abdul-aziz-international-airport_saudi-arabia_6300018
OPKC: karachi-airport_pakistan_6300111
RCSS: taipei-songshan-airport_taiwan_1980019
RJTT: tokyo-international-airport_japan_6300412
RKPK: busan-%2f-gimhae-international-airport_south-korea_6300424
RKSI: incheon-international-airport_south-korea_6300433
RPLL: ninoy-aquino-international-airport_philippines_1701661
SAEZ: ministro-pistarini-international-airport_argentina_6300524
SBGR: s%c3%a3o-paulo%e2%80%93guarulhos-international-airport_brazil_6300629
UUWW: vnukovo-international-airport_russia_6301018
WMKK: kuala-lumpur-international-airport_malaysia_6301255
WSSS: singapore-changi-airport_singapore_1880725
ZBAA: beijing-capital-international-airport_china_6301354
ZGGG: guangzhou-baiyun-international-airport_china_6301359
ZGSZ: shenzhen-bao%27an-international-airport_china_6301365
ZHHH: wuhan-tianhe-international-airport_china_6301368
ZSPD: shanghai-pudong-international-airport_china_6301386
ZSQD: qingdao-liuting-international-airport_china_6301387
ZUUU: chengdu-shuangliu-international-airport_china_6301392
